
version: 1
services:
  - type: web
    name: generador-excusas-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        value: https://192.168.0.211:5000/api
    repo: https://github.com/Seeent/Generador-de-Excusas
    branch: master
    rootDir: Holacaracola

  - type: web
    name: generador-excusas-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
    repo: https://github.com/Seeent/Generador-de-Excusas
    branch: master
    rootDir: generarBack
